### ISSUE TITLE
[Refactor] Improve architecture

### ISSUE THREAD

**Issue by LauraBeatris** [LauraBeatris/github-explorer#8]
## Requested Changes
 - Break the page into more components (Follow the ["Show, don't tell" principle](https://t.co/kiClFLqbtA?amp=1))
 - Define type definitions on separate files, such as `types.ts`
 - Use the https://github.com/soyguijarro/react-storage-hooks package to store values on local storage, since it deals with the cases where local storage is inactive on the browser.
 - Use absolute imports with TS paths
- Use named exports to improve auto-import and nomenclature refactors 

## Motivation

The current architecture doesn't have a good approach regarding the following points:
- Componentization 
- Location of type definitions 
- Use of local storage without verifying its existing

And regarding code style:
- Use of relative ones with multiple levels '../../' and making reading difficult
- Use of `React.FC` instead of explicitly setting the type for the component props. Refer to https://github.com/facebook/create-react-app/pull/8177 in order to see the downsides of using it

## Tasks
- [x] Improve componentization
- [x] Move type definitions to separate files
- [x] Use local storage with hooks packages to avoid accessing it directly 
- [x] Use absolute import paths instead of relative ones with multiple levels '../../'
- [x] Remove `React.FC` and explicitly set the type for the component props. Refer to https://github.com/facebook/create-react-app/pull/8177 in order to see the downsides of using it
